import type { Conversation, Message, User, Workspace } from "@/lib/orbit/types";

export const YOU = "rowan";
export const STORAGE_KEY = "orbit:v1";

export const EMOJIS = [
  "👍",
  "🎉",
  "✅",
  "👀",
  "🔥",
  "🙏",
  "😮",
  "👏",
  "💯",
  "🐛",
  "📌",
  "⏳",
  "😅",
  "🤝",
  "💡",
  "🚀",
] as const;

export const USERS: User[] = [
  {
    id: "rowan",
    name: "Rowan Hale",
    handle: "rowan",
    initials: "RH",
    title: "Product",
    presence: "online",
    status: "Launch desk",
  },
  { id: "priya", name: "Priya Shah", handle: "priya", initials: "PS", title: "Engineering", presence: "online" },
  {
    id: "noah",
    name: "Noah Adeyemi",
    handle: "noah",
    initials: "NA",
    title: "Design",
    presence: "away",
    status: "Reviewing crops",
  },
  { id: "jules", name: "Jules Ortega", handle: "jules", initials: "JO", title: "Program", presence: "online" },
  { id: "lena", name: "Lena Park", handle: "lena", initials: "LP", title: "Design", presence: "online" },
  { id: "samir", name: "Samir Okonkwo", handle: "samir", initials: "SO", title: "Engineering", presence: "offline" },
  { id: "avery", name: "Avery Quinn", handle: "avery", initials: "AQ", title: "Launch", presence: "online" },
  {
    id: "kai",
    name: "Kai Nakamura",
    handle: "kai",
    initials: "KN",
    title: "Support",
    presence: "away",
    status: "On tickets",
  },
  { id: "mina", name: "Mina Brooks", handle: "mina", initials: "MB", title: "Operations", presence: "online" },
  { id: "theo", name: "Theo Marlow", handle: "theo", initials: "TM", title: "Research", presence: "offline" },
];

const ORBIT_MEMBERS = ["rowan", "priya", "noah", "jules", "lena", "samir", "avery", "kai"];

export const SEED_WORKSPACES: Workspace[] = [
  { id: "orbit", name: "Orbit", initials: "OR" },
  { id: "lumen", name: "Lumen", initials: "LU" },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    kind: "channel",
    id: "general",
    workspaceId: "orbit",
    name: "general",
    description: "Company-wide notes and launch timing.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "channel",
    id: "product",
    workspaceId: "orbit",
    name: "product",
    description: "Scope, checklist, and what actually ships.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "channel",
    id: "design",
    workspaceId: "orbit",
    name: "design",
    description: "Reviews, crops, and type.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "channel",
    id: "engineering",
    workspaceId: "orbit",
    name: "engineering",
    description: "Bugs, fixes, and the deploy window.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "channel",
    id: "announcements",
    workspaceId: "orbit",
    name: "announcements",
    description: "Decisions worth pinning.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "channel",
    id: "random",
    workspaceId: "orbit",
    name: "random",
    description: "Not work. Mostly.",
    memberIds: ORBIT_MEMBERS,
  },
  {
    kind: "dm",
    id: "dm-priya",
    workspaceId: "orbit",
    participantIds: ["rowan", "priya"],
  },
  {
    kind: "dm",
    id: "dm-noah",
    workspaceId: "orbit",
    participantIds: ["rowan", "noah"],
  },
  {
    kind: "dm",
    id: "dm-kai",
    workspaceId: "orbit",
    participantIds: ["rowan", "kai"],
  },
  {
    kind: "dm",
    id: "dm-launch",
    workspaceId: "orbit",
    participantIds: ["rowan", "jules", "lena", "avery"],
    title: "Launch crew",
  },
  {
    kind: "channel",
    id: "lumen-general",
    workspaceId: "lumen",
    name: "general",
    description: "A quiet second workspace, so switching is real.",
    memberIds: ["rowan", "mina", "theo"],
  },
];

function stamp(daysAgo: number, hour: number, minute: number) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function msg(input: Omit<Message, "reactions"> & { reactions?: Message["reactions"] }): Message {
  return { reactions: [], ...input };
}

export const SEED_MESSAGES: Message[] = [
  msg({
    id: "gen-kickoff",
    conversationId: "general",
    authorId: "jules",
    createdAt: stamp(2, 9, 12),
    body: "Kicking off launch week. The public post goes Thursday at 10:00 ET if design signs the hero. Drop blockers here instead of side threads.",
  }),
  msg({
    id: "gen-press",
    conversationId: "general",
    authorId: "avery",
    createdAt: stamp(2, 9, 40),
    body: "Press note is with legal. I’ll have a redline back before standup, and I won’t schedule the post until Jules says the hero is locked.",
  }),
  msg({
    id: "gen-checklist",
    conversationId: "general",
    authorId: "rowan",
    createdAt: stamp(2, 11, 5),
    body: "Thanks. I’ll keep the checklist in #product so we aren’t hunting across channels the morning of.",
  }),
  msg({
    id: "gen-hero",
    conversationId: "general",
    authorId: "lena",
    createdAt: stamp(1, 10, 2),
    body: "Hero is approved with the crop Noah posted. Announcement copy can lock.",
    reactions: [{ emoji: "🎉", userIds: ["avery", "jules"] }],
  }),
  msg({
    id: "gen-deploy",
    conversationId: "general",
    authorId: "samir",
    createdAt: stamp(1, 10, 18),
    body: "Deploy window is 9:30–11:00 ET. I’ll be on the rollback. If billing snapshots flake again, we ship anyway and watch the worker.",
  }),
  msg({
    id: "gen-staging",
    conversationId: "general",
    authorId: "priya",
    createdAt: stamp(0, 9, 5),
    body: "Staging looks clean. One flaky snapshot in billing tests, not a launch blocker. Tracking it in #engineering.",
  }),
  msg({
    id: "gen-staging-2",
    conversationId: "general",
    authorId: "priya",
    createdAt: stamp(0, 9, 6),
    body: "Same run, second look: the flake is the billing snapshot only. App boot stayed green.",
  }),
  msg({
    id: "gen-staging-3",
    conversationId: "general",
    authorId: "priya",
    createdAt: stamp(0, 9, 7),
    body: "I’ll leave the test quarantined until after Thursday. Not worth a revert today.",
  }),
  msg({
    id: "gen-shots",
    conversationId: "general",
    authorId: "noah",
    createdAt: stamp(0, 9, 22),
    body: "Marketing screenshots are in the shared folder, named by frame: https://files.example.com/orbit/marketing/launch-week/frames/hero-b-hand-kerned-export-do-not-reexport.png — please don’t re-export them. A single * is not emphasis.",
  }),
  msg({
    id: "gen-social",
    conversationId: "general",
    authorId: "avery",
    createdAt: stamp(0, 9, 40),
    body: "Social is drafted, not scheduled. If we slip past noon I’ll pull the thread rather than let it go out half-true.",
    reactions: [{ emoji: "👍", userIds: ["rowan", "jules"] }],
  }),
  msg({
    id: "prod-scope",
    conversationId: "product",
    authorId: "jules",
    createdAt: stamp(1, 11, 30),
    body: "Scope for this launch is the workspace switcher, message search, and thread replies. Guest accounts are a fast-follow, and I don’t want them in the post.",
  }),
  msg({
    id: "prod-notes",
    conversationId: "product",
    authorId: "rowan",
    createdAt: stamp(1, 16, 5),
    body: "Agreed. Customer-facing notes are in the [launch checklist](https://example.com/orbit-checklist). I’ll trim anything that sounds like a *roadmap*, keep **the *launch* scope** tight, and leave the status line as `final`.",
  }),
  msg({
    id: "prod-draft",
    conversationId: "product",
    authorId: "rowan",
    createdAt: stamp(1, 16, 42),
    body: "Wrote the what’s-new draft so we can stop passing the doc around.\n\nSearch finds messages and the replies inside a thread. Switching conversations keeps an unsent draft. Guest accounts are not in this post.\n\nIf a line sounds like a promise we can’t keep on Thursday, cut it. I’d rather ship a short note than a careful one that overreaches.",
  }),
  msg({
    id: "prod-mention",
    conversationId: "product",
    authorId: "jules",
    createdAt: stamp(0, 10, 14),
    body: "@rowan can you confirm the checklist before 4? Legal wants the “what’s new” bullets, and Avery is holding the post until those are final.",
    reactions: [{ emoji: "👀", userIds: ["avery"] }],
  }),
  msg({
    id: "prod-pair",
    conversationId: "product",
    authorId: "lena",
    createdAt: stamp(0, 10, 26),
    body: "I can pair on the bullets if the design section is still loose. The hero sentence should stay one line.",
  }),
  msg({
    id: "design-hero",
    conversationId: "design",
    authorId: "noah",
    createdAt: stamp(1, 13, 10),
    body: "Reviewing the marketing hero. I tried a tighter crop so the product frame isn’t floating in paper. Look at frame “Launch / Hero B” before you comment on type.",
    reactions: [{ emoji: "👀", userIds: ["lena", "rowan"] }],
  }),
  msg({
    id: "design-r1",
    conversationId: "design",
    authorId: "lena",
    parentId: "design-hero",
    createdAt: stamp(1, 13, 22),
    body: "The crop is better. The caption under the frame is competing with the headline. Can we drop it on desktop?",
  }),
  msg({
    id: "design-r2",
    conversationId: "design",
    authorId: "noah",
    parentId: "design-hero",
    createdAt: stamp(1, 13, 28),
    body: "Yes. I’ll keep the caption on mobile, where the frame is smaller and the headline wraps.",
  }),
  msg({
    id: "design-r3",
    conversationId: "design",
    authorId: "rowan",
    parentId: "design-hero",
    createdAt: stamp(1, 13, 41),
    body: "Drop it on desktop. The headline already says what the screen is. Don’t add a second line to explain the picture.",
  }),
  msg({
    id: "design-r4",
    conversationId: "design",
    authorId: "lena",
    parentId: "design-hero",
    createdAt: stamp(1, 14, 5),
    body: "Updated. Also nudged the plum rail so it doesn’t clip at 1440. The send button and the mention badge were shouting at each other — badge stays small.",
  }),
  msg({
    id: "design-r5",
    conversationId: "design",
    authorId: "noah",
    parentId: "design-hero",
    createdAt: stamp(1, 14, 16),
    body: "Shipping Hero B. I’ll stop moving the frame.",
    reactions: [{ emoji: "✅", userIds: ["rowan", "lena"] }],
  }),
  msg({
    id: "design-type",
    conversationId: "design",
    authorId: "lena",
    createdAt: stamp(1, 15, 2),
    body: "Sidebar type ramp looks right. I’m still unsure the accent should be the only solid fill in the composer. It is, and I think that’s the point.",
  }),
  msg({
    id: "design-accent",
    conversationId: "design",
    authorId: "rowan",
    createdAt: stamp(1, 15, 20),
    body: "They can share one accent. The badge is a few characters. The button is the only solid control. If both yell, we shrink the badge, not the button.",
  }),
  msg({
    id: "design-final",
    conversationId: "design",
    authorId: "noah",
    createdAt: stamp(0, 11, 5),
    body: "Final hero is in the folder. I’ll post the announcement crop once Avery locks the headline — not before.",
    attachments: [{ id: "hero-b", name: "launch-hero-b.png", size: 1843200 }],
  }),
  msg({
    id: "eng-bug",
    conversationId: "engineering",
    authorId: "samir",
    createdAt: stamp(2, 14, 10),
    body: "Checkout retry is firing twice when the card network times out. I think the client and the worker both schedule a retry.",
  }),
  msg({
    id: "eng-repro",
    conversationId: "engineering",
    authorId: "priya",
    createdAt: stamp(2, 15, 22),
    body: "I can reproduce on staging with a forced 504. Looking at `retryBudget` now.",
    reactions: [{ emoji: "🐛", userIds: ["samir"] }],
  }),
  msg({
    id: "eng-budget",
    conversationId: "engineering",
    authorId: "samir",
    createdAt: stamp(1, 11, 48),
    editedAt: stamp(1, 12, 5),
    body: "Retry budget is 3, not 5. The extra attempts were stacking on the worker and that’s what double-charged the test card.",
  }),
  msg({
    id: "eng-fix",
    conversationId: "engineering",
    authorId: "priya",
    createdAt: stamp(1, 12, 30),
    body: "Fixed in the worker. The guard is `if (attempt >= budget) return`. The client still retries once so a dead tab doesn’t lose the payment. Test is in the PR.",
    reactions: [{ emoji: "✅", userIds: ["rowan", "jules"] }],
  }),
  msg({
    id: "eng-notes",
    conversationId: "engineering",
    authorId: "rowan",
    createdAt: stamp(1, 12, 44),
    body: "If that stays green, we don’t mention it in the launch notes. Quiet fixes can stay quiet.",
  }),
  msg({
    id: "ann-date",
    conversationId: "announcements",
    authorId: "jules",
    createdAt: stamp(2, 16, 20),
    body: "Thursday is the date. I’ll put the real sentence in the pin once Avery and legal agree on the wording.",
  }),
  msg({
    id: "ann-pin",
    conversationId: "announcements",
    authorId: "avery",
    createdAt: stamp(1, 9, 5),
    pinned: true,
    body: "Orbit opens to new teams Thursday, 10:00 ET. Shipping: channels, threads, and search. Not shipping: guest accounts. This pin stays through Friday.",
    reactions: [{ emoji: "📌", userIds: ["jules", "rowan"] }],
  }),
  msg({
    id: "ann-hours",
    conversationId: "announcements",
    authorId: "jules",
    createdAt: stamp(1, 17, 10),
    body: "Office hours Friday 4:30 ET if a new team hits a rough edge. I’ll staff it with Priya. Bring the real error, not a paraphrase.",
  }),
  msg({
    id: "ann-headline",
    conversationId: "announcements",
    authorId: "avery",
    createdAt: stamp(0, 8, 50),
    body: "Headline is locked: “Orbit is open.” No exclamation point. If this and the pin ever disagree, the pin wins.",
  }),
  msg({
    id: "ann-support",
    conversationId: "announcements",
    authorId: "kai",
    createdAt: stamp(0, 9, 12),
    body: "Support will copy the pin into the help center after 10:00 ET, not before. I don’t want two versions live at once.",
  }),
  msg({
    id: "rand-puzzle",
    conversationId: "random",
    authorId: "samir",
    createdAt: stamp(1, 17, 40),
    body: "Someone left a puzzle half-done on the table by the window. I will not be the person who finishes it.",
  }),
  msg({
    id: "rand-art",
    conversationId: "random",
    authorId: "avery",
    createdAt: stamp(1, 17, 55),
    body: "Leave it. An unfinished puzzle is the only honest art in this office.",
  }),
  msg({
    id: "rand-coffee",
    conversationId: "random",
    authorId: "kai",
    createdAt: stamp(0, 15, 40),
    body: "The urn on 4 is empty and I am choosing not to be brave about it.",
  }),
  msg({
    id: "rand-pot",
    conversationId: "random",
    authorId: "lena",
    createdAt: stamp(0, 15, 48),
    body: "I’ll bring a pot down. This is my one launch-week contribution to morale.",
    reactions: [{ emoji: "🙏", userIds: ["kai", "noah"] }],
  }),
  msg({
    id: "rand-snacks",
    conversationId: "random",
    authorId: "noah",
    createdAt: stamp(0, 16, 2),
    body: "Hero B is done, so I am officially available for snacks and bad opinions.",
  }),
  msg({
    id: "dm-p1",
    conversationId: "dm-priya",
    authorId: "priya",
    createdAt: stamp(1, 16, 40),
    body: "You around to look at the retry patch before I open it? I care about the double-charge case more than the naming.",
  }),
  msg({
    id: "dm-p2",
    conversationId: "dm-priya",
    authorId: "rowan",
    createdAt: stamp(1, 16, 44),
    body: "Yes. Send the diff. If the test forces a 504 and asserts a single capture, I’m good.",
  }),
  msg({
    id: "dm-p3",
    conversationId: "dm-priya",
    authorId: "priya",
    createdAt: stamp(1, 16, 51),
    body: "Pushed. That’s the assertion. I’ll merge after you glance — no rush past tonight.",
  }),
  msg({
    id: "dm-n1",
    conversationId: "dm-noah",
    authorId: "noah",
    createdAt: stamp(0, 9, 30),
    body: "Hero B is the one. I killed the desktop caption, like we said in the thread.",
  }),
  msg({
    id: "dm-n2",
    conversationId: "dm-noah",
    authorId: "rowan",
    createdAt: stamp(0, 9, 36),
    body: "Looks right. Don’t let the rail clip at 1440 — Lena already caught it once.",
  }),
  msg({
    id: "dm-n3",
    conversationId: "dm-noah",
    authorId: "noah",
    createdAt: stamp(0, 9, 41),
    body: "Already nudged. I’ll stop tinkering.",
  }),
  msg({
    id: "dm-k1",
    conversationId: "dm-kai",
    authorId: "kai",
    createdAt: stamp(0, 14, 12),
    body: "Two teams wrote in asking whether search includes thread replies. I told them I’d confirm before I answer in the help note.",
  }),
  msg({
    id: "dm-k2",
    conversationId: "dm-kai",
    authorId: "kai",
    createdAt: stamp(0, 14, 18),
    body: "Also, one of them thought Later was a snooze. Worth a line so we don’t get tickets about “missing reminders”.",
  }),
  msg({
    id: "dm-k3",
    conversationId: "dm-kai",
    authorId: "rowan",
    createdAt: stamp(0, 14, 26),
    body: "Search includes thread replies. Later is a saved list, not a reminder. You can say both in one sentence.",
  }),
  msg({
    id: "crew-1",
    conversationId: "dm-launch",
    authorId: "jules",
    createdAt: stamp(1, 18, 2),
    body: "Can we do a 15-minute launch desk at 9:40 ET tomorrow? Avery, Lena, Rowan. No slides.",
  }),
  msg({
    id: "crew-2",
    conversationId: "dm-launch",
    authorId: "avery",
    createdAt: stamp(1, 18, 6),
    body: "9:40 works. I’ll have the post in draft mode, not scheduled, until we say go.",
  }),
  msg({
    id: "crew-3",
    conversationId: "dm-launch",
    authorId: "lena",
    createdAt: stamp(1, 18, 11),
    body: "I’ll be there. If Hero B slips I’ll say so at the start, not halfway through.",
  }),
  msg({
    id: "crew-4",
    conversationId: "dm-launch",
    authorId: "rowan",
    createdAt: stamp(1, 18, 20),
    body: "9:40 works. I’ll bring the checklist and nothing else.",
  }),
  msg({
    id: "crew-5",
    conversationId: "dm-launch",
    authorId: "jules",
    createdAt: stamp(0, 9, 2),
    body: "Desk is on. Same link as standup. If you’re late, read the pin in #announcements first.",
  }),
  msg({
    id: "lumen-1",
    conversationId: "lumen-general",
    authorId: "mina",
    createdAt: stamp(3, 11, 0),
    body: "Welcome to Lumen. This workspace is only here so you can leave Orbit and come back. The launch work stays next door.",
  }),
  msg({
    id: "lumen-2",
    conversationId: "lumen-general",
    authorId: "theo",
    createdAt: stamp(3, 11, 20),
    body: "I’ll keep research notes out of Orbit’s #product. If something needs a decision, I’ll write it in a sentence, not a memo.",
  }),
];

function justBefore(messageId: string) {
  const message = SEED_MESSAGES.find((item) => item.id === messageId);
  if (!message) return new Date().toISOString();
  return new Date(new Date(message.createdAt).getTime() - 1000).toISOString();
}

function latestIn(conversationId: string) {
  const items = SEED_MESSAGES.filter((item) => item.conversationId === conversationId);
  return items.reduce((latest, item) => (item.createdAt > latest ? item.createdAt : latest), items[0]?.createdAt ?? new Date().toISOString());
}

export const INITIAL_LAST_READ: Record<string, string> = {
  general: latestIn("general"),
  product: justBefore("prod-mention"),
  design: latestIn("design"),
  engineering: justBefore("eng-budget"),
  announcements: latestIn("announcements"),
  random: justBefore("rand-coffee"),
  "dm-priya": latestIn("dm-priya"),
  "dm-noah": latestIn("dm-noah"),
  "dm-kai": justBefore("dm-k1"),
  "dm-launch": latestIn("dm-launch"),
  "lumen-general": latestIn("lumen-general"),
};

export const AVATAR_CLASS: Record<string, string> = {
  rowan: "bg-avatar-rowan",
  priya: "bg-avatar-priya",
  noah: "bg-avatar-noah",
  jules: "bg-avatar-jules",
  lena: "bg-avatar-lena",
  samir: "bg-avatar-samir",
  avery: "bg-avatar-avery",
  kai: "bg-avatar-kai",
  mina: "bg-avatar-mina",
  theo: "bg-avatar-theo",
};
